[package]
name = "aot-backend"
version = "0.1.0"
edition = "2021"
default-run = "aot-backend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
anyhow = "1.0.53"
derive_more = "0.99.17"
chrono = { version = "0.4.10", features = ["serde"] }
diesel = { version = "1.4.4", features = ["chrono", "postgres", "r2d2"] }
dotenv = "0.15.0"
futures = "0.3.1"
r2d2 = "0.8.8"
serde_derive = "1.0"
serde_json = "1.0"
actix-service = "1.0.1"
actix-session = "0.4.1"
alcoholic_jwt = "1.0.0"
actix-rt = "1.0.0"
flexi_logger = "0.20.1"
log = "0.4.14"
rand = "0.8.4"
rayon = "1.5.1"
thiserror = "1.0.30"
array2d = "0.2.1"
petgraph = "0.5.0"
num-integer = "0.1"
serde = { version = "1.0", features = ["derive"] }
pwhash = "1"
reqwest = { version = "0.10", features = ["blocking", "json"] }
tokio = { version = "0.2.21", features = ["macros"] }
